In [2]:
import numpy as np

In [3]:
numeros_primos=[2,3,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [4]:
array_primos=np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [5]:
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
array_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [9]:
array_impares=array_pares+1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
array_impares*100

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [11]:
array_impares-array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
array_impares/array_pares

/var/folders/cv/d__dx_557kg_0k75cfkhppcr0000gn/T/ipykernel_52963/2727502484.py:1: RuntimeWarning: divide by zero encountered in true_divide
  array_impares/array_pares


array([       inf, 1.5       , 1.25      , 1.16666667, 1.125     ,
       1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556])

In [13]:
array_primos.sum()

129

In [14]:
array_primos.mean()

12.9

In [15]:
array_primos.var()

73.28999999999999

In [16]:
array_fibonacci=np.array([55,0,144,1,21,89,5,8,13,1,34,3,2])
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [17]:
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [18]:
-np.sort(-array_fibonacci)

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

In [19]:
A = np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [20]:
A[0,0]

0

In [21]:
A [1,3]

16

In [22]:
A [1,:]

array([10, 12, 14, 16, 18])

In [23]:
A[:,3]

array([ 6, 16])

In [24]:
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [25]:
array_fibonacci<20

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

In [26]:
array_fibonacci[array_fibonacci<20]

array([ 0,  1,  5,  8, 13,  1,  3,  2])